name: Node.js CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm install

      - run: node -v

      - run: npm -v
